name: Run HTML and Deploy to Pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env: 
        GITHUB_TOKEN: ${{secrets.DASHBOARDTOKEN}}
        SUPER_SECRET: ${{ secrets.SuperSecret }}


    steps:    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    # - shell : bash
    #  run: echo $SUPER_SECRET

    - name: list files
      run: ls -R

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript
      run: npx tsc
    

    - name: Run JavaScript Tests
      run: node src/scripts.js

 
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './src'
      - id: deployment
        uses: actions/deploy-pages@v4

  