name: Run HTML and JavaScript Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run-html-and-js:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript
      run: npx tsc

    # - name: Run JavaScript Tests
    #   run: node src/scripts.js

    # - name: Run HTML Tests with Puppeteer
    #   run: |
    #     npx puppeteer-cli evaluate src/test-html.js
    #   env:
    #     CI: true
